packages:
  - packages/*
  - apps/*

overrides:
  '@tiptap/core': 3.7.2
  '@tiptap/extension-blockquote': 3.7.2
  '@tiptap/extension-bold': 3.7.2
  '@tiptap/extension-bullet-list': 3.7.2
  '@tiptap/extension-code': 3.7.2
  '@tiptap/extension-code-block': 3.7.2
  '@tiptap/extension-color': 3.7.2
  '@tiptap/extension-document': 3.7.2
  '@tiptap/extension-dropcursor': 3.7.2
  '@tiptap/extension-gapcursor': 3.7.2
  '@tiptap/extension-hard-break': 3.7.2
  '@tiptap/extension-heading': 3.7.2
  '@tiptap/extension-highlight': 3.7.2
  '@tiptap/extension-horizontal-rule': 3.7.2
  '@tiptap/extension-italic': 3.7.2
  '@tiptap/extension-link': 3.7.2
  '@tiptap/extension-list': 3.7.2
  '@tiptap/extension-list-item': 3.7.2
  '@tiptap/extension-list-keymap': 3.7.2
  '@tiptap/extension-ordered-list': 3.7.2
  '@tiptap/extension-paragraph': 3.7.2
  '@tiptap/extension-strike': 3.7.2
  '@tiptap/extension-subscript': 3.7.2
  '@tiptap/extension-superscript': 3.7.2
  '@tiptap/extension-text': 3.7.2
  '@tiptap/extension-text-style': 3.7.2
  '@tiptap/extension-underline': 3.7.2
  '@tiptap/extensions': 3.7.2
  '@tiptap/pm': 3.7.2

allowBuilds:
  core-js: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
